Modify build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,50 +3,60 @@
 set -x              # Print command traces before executing command
 trap 'exit 1' ERR   # Exit script with error if command fails
 
-# Validate that docker exists
+cd $(dirname "${BASH_SOURCE[0]}")
+
 if [[ -z $(which docker) ]]; then
     echo "Missing docker client which is required for building, testing and pushing."
     exit 2
 fi
 
-# Set working directory to project root
-cd $(dirname "${BASH_SOURCE[0]}")
 
-# Declarations
 declare IMAGE_NAME="bachelorthesis/jenkins"
 
-# if not run as root user, docker needs sudo
-if [[ $EUID -ne 0 ]]; then
-    alias docker='sudo docker'
-fi
 
-# Build docker image
 function build {
-    # Master
-    docker build -t "${IMAGE_NAME}:latest" master
-    docker build -t "${IMAGE_NAME}:master" master
-    # Slave
-    docker build -t "${IMAGE_NAME}:slave" slave
-}
+    version="${1}"
+    
+    if [ "$version" -eq "master" ]; then
+        docker build -t "${IMAGE_NAME}:latest" master
+        docker build -t "${IMAGE_NAME}:master" master
+    
+    elif [ "$version" -eq "slave" ]
+        docker build -t "${IMAGE_NAME}:slave" slave
 
-# Test docker image
-function test {
-	docker history $IMAGE_NAME 2> /dev/null
-    if [ $? -eq 1 ]; then
-        echo "Cant test $IMAGE_NAME, the image does not exist."
+    else
+        echo "$version does not exist."
         exit 2
     fi
-    
-    #Run tests
-    bats test/
 }
 
-# Push docker image to docker hub
-function push {
-	docker history $IMAGE_NAME 2> /dev/null
+
+function test {
+    version="${1}"
+
+    docker history "${IMAGE_NAME}:${version}" 2> /dev/null
 
     if [ $? -eq 1 ]; then
-        echo "Cant push $IMAGE_NAME, the image does not exist."
+        echo "Cant test ${IMAGE_NAME}:${version}, the image does not exist."
+        exit 2
+    fi
+
+    if [[ -z $(which bats) ]]; then
+        echo "Missing bats, which is required for testing."
+        exit 2
+    fi
+
+    bats "test/jenkins-${version}.bats"
+}
+
+
+function push {
+    version="${1}"
+
+    docker history "${IMAGE_NAME}:${version}" 2> /dev/null
+
+    if [ $? -eq 1 ]; then
+        echo "Cant push ${IMAGE_NAME}:${version}, the image does not exist."
         exit 2
     fi
 
@@ -54,17 +64,49 @@ function push {
     [ -z "$DOCKER_USER" ]     && { echo "Need to set DOCKER_USER";     exit 1; }
     [ -z "$DOCKER_PASSWORD" ] && { echo "Need to set DOCKER_PASSWORD"; exit 1; }
 
-    sudo docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
-    # Master
-    sudo docker push "${IMAGE_NAME}:latest"
-	sudo docker push "${IMAGE_NAME}:master"
-    # Slave
-    sudo docker push "${IMAGE_NAME}:slave"
+    if [[ $EUID -ne 0 ]]; then
+        sudo docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
+        sudo docker push "${IMAGE_NAME}:${version}"
+
+        if [ "$version" -eq "master" ]; then
+            sudo docker push -t "${IMAGE_NAME}:latest" master
+        fi
+
+    else
+        docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
+        docker push "${IMAGE_NAME}:${version}"
+
+        if [ "$version" -eq "master" ]; then
+            sudo docker push -t "${IMAGE_NAME}:latest" master
+        fi
+    fi
+
 }
 
-# Handle user input, if no arguments are given, run all functions.
-# Valid arguments are: make_rootfs, build, test and push
+
+#
+# Handle input
+#
+
+versions=()
 actions=("$@")
+
+while getopts ":v:" opt; do
+  case $opt in
+    v)
+      versions+=("$OPTARG")
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG"
+      ;;
+  esac
+done
+
+if [ ${#versions[@]} -eq 0 ]; then
+    versions+=(master)
+    versions+=(slave)
+fi
+
 if [ ${#actions[@]} -eq 0 ]; then
     actions=(build test push)
 fi
@@ -72,19 +114,21 @@ fi
 for action in "${actions[@]}"; do 
     case "$action" in
         build)
-            build
+            for version in "${versions[@]}"; do
+               build $version
+            done
             ;;
          
         test)
-            test
+            for version in "${versions[@]}"; do
+               test $version
+            done
             ;;
 
         push)
-            push
+            for version in "${versions[@]}"; do
+               push $version
+            done
             ;;
-         
-        *)
-            echo $"Usage: $0 {build || test || push}"
-            exit 1
     esac
 done
